# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Re-create documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools mkdocs
    - name: Run mkdocs --clean
      run: |
        ls
        mkdocs build --clean
        
    - name: Push to documentation repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
          source-directory: 'site'
          destination-github-username: 'EvilOlaf'
          destination-repository-name: 'docutest'
          user-email: werner@armbian.de
        
        
    - name: Upload artefact 
      uses: actions/upload-artifact@v2
      with:
        name: docu-${{ GITHUB_SHA }}
        path: site/ 
        

